name: Lint and Test

on:
  workflow_call:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: '.node-version'

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format -- --error-on-warnings

      - name: Lint
        run: npm run lint -- --error-on-warnings

      - name: Test
        run: npm run test
