name: PR CI

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  publish-alpha:
    needs: lint-and-test
    uses: ./.github/workflows/alpha-publish.yml
    secrets: inherit
